import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Button from '../../components/Button';
import Cta from '../../components/Cta';
import Div from '../../components/Div';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import SectionHeading from '../../components/SectionHeading';
import Spacing from '../../components/Spacing';

export default function PortfolioDetails() {
  const router = useRouter();
  const portfolioId = router.query.portfolioId;
  return (
    <>
      <Head>
        <title>Portfolio - {portfolioId}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <PageHeading
          title="Portfolio Details"
          bgSrc="/images/service_hero_bg.jpeg"
          pageLinkText={portfolioId}
        />
        <Spacing lg="150" md="80" />
        <Div className="container">
          <img
            src="/images/portfolio_details_1.jpeg"
            alt="Details"
            className="cs-radius_15 w-100"
          />
          <Spacing lg="90" md="40" />
          <Div className="row">
            <Div className="col-lg-6">
              <SectionHeading title="Spotd2d" subtitle="Creative">
                <Spacing lg="40" md="20" />
                <p>
                Spotd2d is a fantastic food application created by Natalnine that offers users a seamless food ordering experience. With Spotd2d, customers can easily browse through an extensive collection of restaurants and their menus, select their favourite dishes, and place orders with just a few taps. 
                </p>
                <Spacing lg="10" md="10" />
                <p>
                The app also allows users to customise their orders, track their delivery status in real-time, and provide feedback. With its user-friendly interface and impressive features, Spotd2d is a must-have application for anyone who loves delicious food and convenience.
                </p>
              </SectionHeading>
            </Div>
            <Div className="col-lg-5 offset-lg-1">
              <Spacing lg="60" md="40" />
              <h2 className="cs-font_30 cs-font_26_sm cs-m0">Project Info -</h2>
              <Spacing lg="50" md="30" />
              <Div className="row">
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Category:
                  </h3>
                  <p className="cs-m0">Ecommerce</p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Location:
                  </h3>
                  <p className="cs-m0">KanyaKumari </p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Technology
                  </h3>
                  <p className="cs-m0">Laravel</p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Dated:
                  </h3>
                  <p className="cs-m0">Feb 2023</p>
                  <Spacing lg="30" md="30" />
                </Div>
                <Div className="col-6">
                  <h3 className="cs-accent_color cs-font_22 cs-font_18_sm cs-m0">
                    Client:
                  </h3>
                  <p className="cs-m0">Andreo Bowla</p>
                  <Spacing lg="30" md="30" />
                </Div>
              </Div>
            </Div>
          </Div>
          <Spacing lg="65" md="10" />
          <Div className="cs-page_navigation cs-center">
            <Div>
              <Button
                btnLink="/portfolio/portfolio-details"
                btnText="Prev Project"
                variant="cs-type1"
              />
            </Div>
            <Div>
              <Button
                btnLink="/portfolio/portfolio-details"
                btnText="Next Project"
              />
            </Div>
          </Div>
        </Div>
        <Spacing lg="145" md="80" />
        <Cta
          title="info@natalnine.com"
          bgSrc="/images/cta_bg_2.jpeg"
          variant="rounded-0"
        />
      </Layout>
    </>
  );
}
