import Head from 'next/head';
import React from 'react';
import Hero7 from '../components/Hero/Hero7';
import Layout from '../components/Layout';

export default function CaseStudyShowcase() {
  const heroSocialLinks = [
    {
      name: 'Behance',
      links: '/',
    },
    {
      name: 'Twitter',
      links: '/',
    },
  ];

  const showcaseData = [
   
    {
      title: 'Web software <br />Development.',
      imgUrl: '/webdev/2.jpg',
      href: '/case-study-details',
    },
    {
      title: 'Blockchain <br />Development.',
      imgUrl: '/blockchain/1.jpg',
      href: '/case-study-details',
    },
    {
      title: 'Site Reliability <br />Engineering.',
      imgUrl: '/cloud/2.jpg',
      href: '/case-study-details',
    },
    {
      title: 'Mobile App <br />Development',
      imgUrl: '/mobile/2.jpg',
      href: '/mobile-application-development',
    },
    {
      title: 'Digital <br />Marketing',
      imgUrl: '/marketing/2.jpg',
      href: '/digital-marketing',
    },
  ];
  return (
    <>
      <Head>
        <title>Home - Case Study Showcase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero7
          heroSocialLinks={heroSocialLinks}
          socialLinksHeading="Follow Us"
          showcaseData={showcaseData}
        />
      </Layout>
    </>
  );
}
