import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../components/Cta';
import Div from '../components/Div';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';

export default function CaseStudyDetails() {
    return (
        <>
            <Head>
                <title>Web Application Development | NATAL NINE</title>
                <meta name="description" content="Generated by Natalnine" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <PageHeading
                    title="Web Application Development"
                    bgSrc="/images/contact_hero_bg.jpeg"
                    pageLinkText=" "
                />
                <Spacing lg="25" md="80" />
                <Div className="container">

                    <Spacing lg="90" md="45" />
                    <img
                        src="/images/web1.jpg"
                        alt="Thumb"
                        className="w-100 cs-radius_15"
                    />
                    <Spacing lg="140" md="80" />
                    <h2 className="cs-font_38 text-center">What is Web Application Development ?</h2>
                    <Spacing lg="60" md="45" />
                    <p className="cs-m0">
                        Web application development involves creating application programs that are hosted on remote servers and delivered to the user's device via the Internet. Unlike traditional applications, web apps do not require downloading and can be accessed through a web browser such as Google Chrome, Safari, or Mozilla Firefox. JavaScript, Cascading Style Sheets (CSS), and HTML5 are commonly used to develop web applications.
                        <br /><br />

                        Typically, web application development has a short life-cycle and is led by a small team. Client-side programming, which involves using HTML, CSS, and JavaScript to create the front-end of a web application, is executed on the user's computer through a web browser. HTML is used to display on-screen content, CSS ensures proper formatting, and JavaScript allows for interactive content.
                        <br />
                        <br />

                        Server-side programming supports client-side programming and is responsible for creating the scripts used by web applications. These scripts can be written in various scripting languages, such as Ruby, Java, and Python. Server-side scripting is used to create a customized interface for the end-user and to conceal the source code that underlies the interface.
                    </p>
                    <Spacing lg="65" md="45" />
                    <Div className="row">
                        <Div className="col-sm-6">
                            <img
                                src="/images/web5.jpg"
                                alt="Thumb"
                                className="w-100 cs-radius_5"
                            />
                            <Spacing lg="25" md="25" />
                        </Div>
                        <Div className="col-sm-6">
                            <img
                                src="/images/web3.jpg"
                                alt="Thumb"
                                className="w-100 cs-radius_5"
                            />
                            <Spacing lg="25" md="25" />
                        </Div>
                    </Div>
                    <Spacing lg="125" md="55" />
                </Div>
                <Div className="cs-gradient_bg_1 cs-shape_wrap_6">
                    <Div className="cs-shape_2"></Div>
                    <Div className="cs-shape_2"></Div>
                    <Div className="container">
                        <Spacing lg="35" md="80" />
                        <h2 className="cs-font_38 text-center">  </h2>
                        <Spacing lg="10" md="45" />
                        <Div className="row align-items-center cs-column_reverse_lg">
                            <Div className="col-lg-5">
                                <h3 className="cs-font_30 cs-m0">What's the Difference Between a Web App and a Wesbite?</h3>
                                <Spacing lg="45" md="30" />
                                <p className="cs-m0">
                                    Web apps are designed to be interactive, which is different from the primary purpose of a website, which is to present information. Learning about mobile development can be helpful for understanding web app development. For example, you should know the difference between native and hybrid apps. Native apps are platform-specific and require the use of native technologies, such as Swift for iOS and Java for Android. However, developing different apps for different platforms can be a disadvantage. Hybrid apps, on the other hand, use both native and web technologies, making them more compatible with multiple platforms.

                                </p>
                            </Div>
                            <Div className="col-lg-6 offset-lg-1 text-center">
                                <Div className="cs-portfolio_img_in cs-shine_hover_1 rounded-circle">
                                    <img
                                        src="/images/web2.jpg"
                                        alt="Case study"
                                        className="w-100"
                                    />
                                </Div>
                                <Spacing lg="0" md="40" />
                            </Div>
                        </Div>
                        <Spacing lg="100" md="80" />
                        <Div className="row align-items-center">
                            <Div className="col-lg-6 text-center">
                                <Div className="cs-portfolio_img_in cs-shine_hover_1 rounded-circle">
                                    <img
                                        src="/images/web.jpg"
                                        alt="Case study"
                                        className="w-100"
                                    />
                                </Div>
                                <Spacing lg="0" md="40" />
                            </Div>
                            <Div className="col-lg-5 offset-lg-1">
                                <h3 className="cs-font_30 cs-m0">What Are Progressive Web Apps (PWAs)?</h3>
                                <Spacing lg="45" md="30" />
                                <p className="cs-m0">
                                PWAs are a type of web application that is relatively modern and combines features of native and hybrid apps. While PWAs are accessed through a web browser like any other web app, users must download and install them like a mobile app. However, this is a benefit as PWAs can be quickly accessible from the user's device. The Google Play Store and the Microsoft Store both support PWAs, so they can function as mobile apps in some ways. PWAs have the advantage of launching directly from a user's device without opening a browser, and they can send push notifications and work offline while loading quickly.
                                </p>
                            </Div>
                        </Div>
                        <Spacing lg="150" md="80" />
                    </Div>
                </Div>
                <Spacing lg="140" md="80" />
                <Div className="container text-center">
                    <Div className="row col-lg-10 offset-lg-1">
                        <h2 className="cs-font_38 cs-m0">Types of Web Applications</h2>
                        <Div className="container text-start" style={{ paddingLeft: "350px" }}>
                        <Spacing lg="60" md="45" />
                        <p className="cs-m0">
                        <li>Enterprise web apps</li> 
                        <li>Web portals</li> 
                        <li>Customer-facing apps</li> 
                        <li>Supply chain management web apps</li> 
                        <li>Online services</li> 
                        <li>Ecommerce Website</li> 
                        <li>Web apps for healthcare</li> 
                        <li>Analytics web apps</li> 
                   


                        </p>
                    </Div>
                    </Div>
                </Div>
                <Spacing lg="145" md="80" />
                {/* Start CTA Section */}
                <Div className="container">
                    <Cta
                        title="Let’s disscuse make <br />something <i>cool</i> together"
                        btnText="Apply For Meeting"
                        btnLink="/contact"
                        bgSrc="/images/cta_bg.jpeg"
                    />
                </Div>
                {/* End CTA Section */}
            </Layout>
        </>
    );
}
